### ISSUE TITLE
xdc文件无法高亮显示

### ISSUE THREAD

**Issue by beckybecky111** [Digital-EDA/Digital-IDE#10]
如图所示：
![image](https://github.com/Digital-EDA/Digital-IDE/assets/64124905/8d3beafa-ad35-405d-bcf7-3964853174b2)

**Comment by LSTM-Kirigaya** [comment]
你可以试试其他的主题颜色，不过我们仍然会积极将xdc脚本的高亮覆盖大部分主题。我会在默认主题下完成xdc脚本的高亮和自动补全后关闭这个issue，谢谢您的反馈。
