### ISSUE TITLE
[0.3.0 beta] iverilog指令错误

### ISSUE THREAD

**Issue by DuBirdFly** [Digital-EDA/Digital-IDE#14]
当文件中多次例化同一模块时, "快速iverilog"生成的指令会重复添加该模块

![Snipaste_2023-08-28_23-23-57](https://github.com/Digital-EDA/Digital-IDE/assets/98462076/d0d2d005-019b-404f-a720-8f75b19a52ba)

**Comment by LSTM-Kirigaya** [comment]
已经修复这个问题，谢谢您的反馈！
