### ISSUE TITLE
在架构里不能解析include后的模块

### ISSUE THREAD

**Issue by beckybecky111** [Digital-EDA/Digital-IDE#17]
在层级结构中include的模块不能正确解析，另外每次重新打开文件夹，都需要重新设置TOP。

![image](https://github.com/Digital-EDA/Digital-IDE/assets/64124905/f609f333-53a1-40f3-8bd5-a320b21398df)

**Comment by LSTM-Kirigaya** [comment]
层次显示中，只有你在当前 TOP 模块中例化的才会被显示，层次树并不显示你 include 进来的文件。如果你在 TOP.v 的 TOP 模块中确实例化了图中所有 include 进来的文件，但是 tree 没有对应的响应，那么确实是我们的 bug，请您再次确认一下 TOP 模块内的具体内容。如果方便的话，可以修改后公开一部分脱敏内容让我们进行问题复现。

**Comment by Nitcloud** [comment]
我们需要更多的反馈来知道您是否已经解决该问题，如果一周之后无更多反馈我们将认为您已解决，我们将关闭此issue，如果你有其他问题，可以重启该issue。
