### ISSUE TITLE
code to doc

### ISSUE THREAD

**Issue by Hqf2013** [Digital-EDA/Digital-IDE#21]
注释显示的逻辑比较奇怪，而且有问题
![image](https://github.com/Digital-EDA/Digital-IDE/assets/9183373/444cf824-5489-461d-9678-440901554f68)

**Comment by LSTM-Kirigaya** [comment]
我们已经成功复现并修复了这个问题，下一个版本提交：
![image](https://github.com/Digital-EDA/Digital-IDE/assets/59416203/4a04af63-c176-49a8-a60e-5c3e95c07f8b)
