### ISSUE TITLE
语法识别错误

### ISSUE THREAD

**Issue by Hqf2013** [Digital-EDA/Digital-IDE#22]
generate后面跟着begin会提示错误，感觉是内部的关键词提醒错误了，里面出现了endgenerate
![image](https://github.com/Digital-EDA/Digital-IDE/assets/9183373/406e3256-7a3e-4deb-9456-2a49b41ca85d)

**Comment by LSTM-Kirigaya** [comment]
抱歉，您提供的样例中，generate的语法是错误的，generate与endgenerate构成一个闭环，语法并不支持在外面套一层 begin end
