### ISSUE TITLE
仿真时因为文件夹名字存在空格产生错误

### ISSUE THREAD

**Issue by Muione** [Digital-EDA/Digital-IDE#24]
[Run - 18:31:39] Create vvp to c:/Users/xxx/OneDrive/OneDrive - xxx/prj/simulation/icarus/out.vvp
[Run - 18:31:39] vvp c:/Users/xxx/OneDrive/OneDrive - xxx/prj/simulation/icarus/out.vvp
[Error - 18:31:39] Error took place when run vvp c:/Users/xxx/OneDrive/OneDrive - xxx/prj/simulation/icarus/out.vvp
[Error - 18:31:39] Reason: c:/Users/xxx/OneDrive/OneDrive: Unable to open input file.

这是在windows平台：
报错产生原因为调用vvp时，传入文件绝对路径中含有空格，是否可以将传入路径外加双引号。我实测自己调用vvp时加上双引号可以在终端运行。
似乎不只是仿真时，很多命令都会因为上述原因产生错误。

**Comment by LSTM-Kirigaya** [comment]
好的，这个问题已经解决
