### ISSUE TITLE
[0.3.2] 例化模块的类型，模块名称的代码高亮不变色

### ISSUE THREAD

**Issue by DreamLand7707** [Digital-EDA/Digital-IDE#35]
如图所示，模块类型和模块名称，0.3.1版本是会变色的，但现在不变色了。
![image](https://github.com/Digital-EDA/Digital-IDE/assets/93921557/a3f70f16-271c-4905-b1f0-1c011b56d3bf)

**Comment by Nitcloud** [comment]
目前还是这个情况吗

**Comment by Nitcloud** [comment]
我们已更新了新的版本0.3.3，如果还遇到同样的问题请在此留言，一周之后我们将关闭此问题，并视为您的问题已被解决。如果已被关闭且未解决，您可以重新打开此问题。
