### ISSUE TITLE
[0.3.2] 代码补全有多个内容完全相同的选项

### ISSUE THREAD

**Issue by DreamLand7707** [Digital-EDA/Digital-IDE#36]
如图所示，输入cl会出现多了相同的clk,影响代码补全的正常使用。
![image](https://github.com/Digital-EDA/Digital-IDE/assets/93921557/78241e4c-400a-4d75-a008-3c34ca26ae4a)
![image](https://github.com/Digital-EDA/Digital-IDE/assets/93921557/63167ad5-6896-4afe-a6d7-197532a23f8f)

**Comment by DreamLand7707** [comment]
摸索出来一个规律，这个东西和always块有关系：

![image](https://github.com/Digital-EDA/Digital-IDE/assets/93921557/67d01501-ab54-4274-8425-e876b7035391)

我在1处写下next_ , ctrl + space:
![image](https://github.com/Digital-EDA/Digital-IDE/assets/93921557/b00bdf44-c648-47d3-9bd9-eb1e68b12193)
一切正常

删除
再次在1处写下next_, ctrl + space
![image](https://github.com/Digital-EDA/Digital-IDE/assets/93921557/d697e859-8ad0-4cc3-aa15-e50d0a26dc53)
正常

删除
在2处操作：
![image](https://github.com/Digital-EDA/Digital-IDE/assets/93921557/69f0a3ef-d509-47c9-b949-36d280edc4f8)
出现了重复解析，两次

删除，再次在2处操作
![image](https://github.com/Digital-EDA/Digital-IDE/assets/93921557/20044b19-d508-47ea-9f07-f675bc72a2cb)
仍然重复解析，两次，情况没变

删除，在1处操作
![image](https://github.com/Digital-EDA/Digital-IDE/assets/93921557/1c380a09-76b5-45a6-aff3-d8a873868402)
仍然有重复解析，两次

删除，在3处操作：
![image](https://github.com/Digital-EDA/Digital-IDE/assets/93921557/27f79c67-8e8d-419a-a0b7-e744b416b704)
重复解析，三次，加了一次

删除，在2处操作：
![image](https://github.com/Digital-EDA/Digital-IDE/assets/93921557/e0517629-7b5a-4751-a431-330f04d8c1ee)
重复解析，三次

删除，在1处操作：
![image](https://github.com/Digital-EDA/Digital-IDE/assets/93921557/e9c687a4-2b28-46f1-8670-827359df792e)
重复解析，三次

删除，在2处重新操作
![image](https://github.com/Digital-EDA/Digital-IDE/assets/93921557/d8a5686c-c109-461b-b68a-ff00bcd9f462)
重复解析，四次

和always块，解析顺序，之前写过的位置和当前写入的位置都有关系。

**Comment by LSTM-Kirigaya** [comment]
感谢您事无巨细的描述，我们会尽快修改并附上 release
