### ISSUE TITLE
[0.3.0 beta] 文件跳转功能失效

### ISSUE THREAD

**Issue by qgzln** [Digital-EDA/Digital-IDE#4]
1文件跳转功能不能使用，左边的
![UKX@KATBRRDNCEQJB6)P2P6](https://github.com/Digital-EDA/Digital-IDE/assets/47837258/b536d9d7-fe3b-4c83-a581-0884e3cf04f6)
这些文件都可以出现，并点击进入，但是在top文件里不能通过跳转文件进入到这些文件里
2 点击
![K9E(S(IY3{ C@OQEGNCX}CX](https://github.com/Digital-EDA/Digital-IDE/assets/47837258/73e4b52e-3eee-4652-971e-4bf123d6c9aa)
z
会报错：
![XX8656SFU}JA(GW@0F)}CAE](https://github.com/Digital-EDA/Digital-IDE/assets/47837258/e5e990fa-af1f-439b-bb74-aa20af50366c)

**Comment by qgzln** [comment]
点击文件跳转的话，在输出那里会显示：
![JP$ 8S1(KVJBZ5DR9X8K C0](https://github.com/Digital-EDA/Digital-IDE/assets/47837258/56413f1c-bb32-49c0-aa85-dceeceb8594a)

**Comment by LSTM-Kirigaya** [comment]
尝试更新vscode版本后，可以解决 :D
