### ISSUE TITLE
插件文档导出问题

### ISSUE THREAD

**Issue by lancyjk** [Digital-EDA/Digital-IDE#67]
0.3.3版本dark主题，文档预览正常，导出pdf缺少箭头（html文件有类似问题）。所有的文档导出md格式文件格式乱码，框图部分显示不正常，其余部分正常。部分文件预览报错，显示Cannot read properties of undefined (reading 'type')，出现问题的文件都较大，一个文档1000+行，一个文档将近3000行

**Comment by lancyjk** [comment]
部分大文件不能生成文档模板，经测试当input的数量小于output的数量就不能生成，很奇怪

**Comment by LSTM-Kirigaya** [comment]
原本不支持在黑色主题下导出 pdf， 0.3.4 开始已经支持。你说的大文件的问题，我们正在排查。

**Comment by LSTM-Kirigaya** [comment]
已经修复，但是给一个建议，我们的 IDE 会自动识别你的 port 申明上下行的单行注释，并作为 description 填入文档化的表格中：


![image](https://github.com/Digital-EDA/Digital-IDE/assets/59416203/920d7143-f262-42d5-af57-a817bf3aee01)
