### ISSUE TITLE
[0.3.0 beta] "定义跳转"定义位置出错

### ISSUE THREAD

**Issue by Nitcloud** [Digital-EDA/Digital-IDE#8]
测试文件：https://github.com/Digital-EDA/Digital-IDE/blob/main/src/test/user/Hardware/src/mult_module.v
. 后面跟的标识符应该到模块定义的地方去找，而不是本地定义的地方
![image](https://github.com/Digital-EDA/Digital-IDE/assets/38045864/0c9db5e7-ae1e-4558-b3f7-72ebb4f67043)
clk在模块中有定义，但是无法跳转。

**Comment by LSTM-Kirigaya** [comment]
thanks，我们会尽快解决
