### ISSUE TITLE
Ubuntu环境下，digital ide对配置环境有问题。

### ISSUE THREAD

**Issue by Asura0609** [Digital-EDA/Digital-IDE#9]
在插件中添加了vivado的安装路径，同时也在系统环境中添加了环境变量
![图片](https://github.com/Digital-EDA/Digital-IDE/assets/100571314/45ab4e0e-7175-4a65-9a70-4e51b4c1366a)
![图片](https://github.com/Digital-EDA/Digital-IDE/assets/100571314/42173b79-b7b3-41c3-8860-1007f140fe86)
![图片](https://github.com/Digital-EDA/Digital-IDE/assets/100571314/1caa7264-3702-4467-9986-49e0557b0edc)

**Comment by LSTM-Kirigaya** [comment]
请问您是哪一个功能无法使用？

**Comment by Nitcloud** [comment]
我们已更新了新的版本0.3.3，如果还遇到同样的问题请在此留言，一周之后我们将关闭此问题，并视为您的问题已被解决。如果已被关闭且未解决，您可以重新打开此问题。
